### ISSUE TITLE
Hashtag in video title crashes the downloader

### ISSUE THREAD

**Issue by mfocht** [alex73630/Floatplane-Downloader#10]
This video https://linustechtips.com/main/topic/890675-tampongate/ causes the downloader to fail.  If I change the number of videos downloaded to exclude this one, it works great.

**Comment by alex73630** [comment]
I've checked it, the issue is because the script search for a 3 letter word before a dash, because of the name scheme for each videos. 
It's a known bug that was planned to be patched with the rework of the script, but as I said in the [v0.1.2 release notes](https://github.com/alex73630/Floatplane-Downloader/releases/tag/v0.1.2), I've decided to not update or fix this project anymore because of the Floatplane.com launch and because of lack of time to maintain this project, I *may* work on it if there is a download feature on the site.

**Comment by mfocht** [comment]
Ah, I must have missed that.  Thanks for your work!
