### ISSUE TITLE
DVRed Livestreams and FP Exclusive are not categorized/downloaded. [ISSUE,IDEA,FIX]

### ISSUE THREAD

**Issue by RyoisMC** [alex73630/Floatplane-Downloader#9]
The Razer Phone announcement live stream shows up as undefinedundefined. 
Some Floatplane Exclusives are not being downloaded. 
My workaround: LINES 199-201 and 211-213
```
function parseTypeForTitle(type){
        if (type == "LTT") {
                return "Linus Tech Tips"
        } else if (type == "CSF") {
                return "Channel Super Fun"
        } else if (type == "TQ") {
                return "Techquickie"
        } else if (type == "Stream")  {  \\CHANGES
                return "Stream"               \\CHANGES
        }                                               \\CHANGES

}
function videoTypeFolderFun(type) {
        if (type == "LTT") {
                return config.lttFolderName
        } else if (type == "CSF") {
                return config.csfFolderName
        } else if (type == "TQ") {
                return config.tqFolderName
        } else if (type == "Stream") {     \\CHANGES
                return config.sFolderName  \\CHANGES
        }                                                      \\CHANGES
}
```
and 
```
{
        "auth": "<email>",
        "password": "<password>",
        "videoQuality": "1080",
        "plexFolder": "/storage/RAID4TB/PLEX/<personalinfo>/Floatplane Media/",
        "lttFolderName": "Linus Tech Tips/",
        "tqFolderName": "Techquickie/",
        "csfFolderName": "Channel Super Fun/",
        "sFolderName": "Streams/"
}
```
After this the Live Streams would be sorted into a folder and the prefix would be Stream

**Comment by alex73630** [comment]
From last release [v0.1.2](https://github.com/alex73630/Floatplane-Downloader/releases/tag/v0.1.2):

> Little reminder: This script only supports LMG regular releases (LinusTechTips/Techquickie/Channel Super Fun) and so it won't download Bitwit Ultra releases (I don't have a subscription) or LMG Floatplane exclusives videos (because of some issues on an unreleased dev build, it downloaded a full livestream that was uploaded on the platform...).
>
> This is unlikely to be changed as Floatplane.com will be launch Soon™. Also, this script won't be updated after Floatplane.com launch if there is no more download feature or if a Plex Channel is planned. That's why v0.2.0 is still WIP and will still be.

As written, I'll not fix it on the master branch as it add huge videos that aren't always watched by everyone. But it was originally planed for v0.2.0, every videos that weren't detected as "regular release" would be tagged "Unsorted" and can be downloaded if the user want it to. (with the possibility to auto-download them) 

One last note: There is a lot of stuff to modify to make it possible in this version, as it only downloads videos where the post title starts with `XXX:` (like `LTT:` `TQ:` or `CSF:`, it's regex stuff) and where there is an actual download button on this page. So there is no easy possibility to just keep streams or FP exclusives with filters because they never keep a specific title for those videos that I could "Regex" (or recognize a pattern)

If you want to modify it, to at least get everything that isn't a "regular release", you would also have to modify a lot of stuff:
- Function [parsingType()](https://github.com/alex73630/Floatplane-Downloader/blob/c87234346ae28154fdcfcb0879389a73e2d5c73b/index.js#L104)
- The [JSON generator](https://github.com/alex73630/Floatplane-Downloader/blob/c87234346ae28154fdcfcb0879389a73e2d5c73b/index.js#L154) (at least some parts)
- Some other stuff...

Definitive word, will not be fixed and will not provide any kind of support for this (as for now).

**Comment by alex73630** [comment]
Closing #9

**Comment by alex73630** [comment]
close #9
